# Generated by Django 4.2.19 on 2025-02-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col1', models.IntegerField()),
                ('col2', models.EmailField(max_length=254)),
                ('col3', models.CharField(max_length=2)),
                ('col4', models.IntegerField()),
                ('col5', models.CharField(max_length=255)),
            ],
        ),
    ]
